services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    image: softvence/${PACKAGE_NAME}:latest
    container_name: admin
    networks:
      - jdadzok_netork

networks:
  jdadzok_netork:
        driver: bridge
